# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  timeout: 10m
  concurrency: 8
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  revive:
    severity: warning
    confidence: 0.8
    errorCode: 0
    warningCode: 0
    # Enable all available rules
    enableAllRules: true
    rule.unexported-return:
      - disabled: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  goimports:
    local-prefixes: github.com/psolru/mikrotik-exporter
  errchek:
    check-type-assertions: false
  nakedret:
    max-func-lines: 30
  gocritic:
    enabled-checks:
      - appendAssign
      - caseOrder
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - flagDeref
      - assignOp
      - captLocal
      - defaultCaseOrder
      - elseif
      - ifElseChain
      - regexpMust
      - singleCaseSwitch
      - sloppyLen
      - switchTrue
      - typeSwitchVar
      - underef
      - unslice
      - commentedOutCode
      - commentedOutImport
      - hugeParam

linters:
  disable-all: true
  enable:
    - gocritic
    - revive
    - govet
    - errcheck
    - dupl
    - ineffassign
    - typecheck
    - goconst
    - goimports
    - staticcheck
    - gosimple
    - gosec
    - unparam
    - bodyclose
    - unconvert
    - unused
    - prealloc
    - exportloopref

issues:
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    - G104
    # for "public interface + private struct implementation" cases only!
    - exported func .* returns unexported type .*, which can be annoying to use
    # can be removed in the development phase
    # - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    # not for the active development - can be removed in the stable phase
    - should have a package comment, unless it's in another file for this package
    - don't use an underscore in package name
    # EXC0001 errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked
    - should check returned error before deferring
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - goconst
        - gocyclo
        - errcheck
        - dupl
        - gosec
