version: "3"

services:
  prom_mikrotik_exporter:
    image: psolru/mikrotik-exporter:latest # replace version for latest version
    volumes:
      - './config:/config'
    env_file: .env
    ports:
      - "9436:9436"
    restart: unless-stopped
